config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'cocktails/search', to: 'cocktails#search', as: :search
  resources :cocktails do
    resources :doses, only: [:create]
    resources :reviews, only: [:create]
  end
  resources :doses, except: [ :create, :show]
  resources :reviews, except: [ :create, :show]
  root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, presence: true, uniqueness: { scope: :ingredient_id}
  validates :ingredient_id, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
  before_destroy :check_doses

  def check_doses
    doses.count == 0
  end
 end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :name, presence: true
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def search
    @search = params.dig(:search, :name)
    @cocktails = Cocktail.where('name ILIKE ?', "%#{@search}%")
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = Cocktail.find(@dose.cocktail_id)
    @dose.delete
    redirect_to cocktail_path(@cocktail)
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @review = Review.new(review_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @review = Review.find(params[:id])
    @cocktail = Cocktail.find(@review.cocktail_id)
    @review.delete
    redirect_to cocktail_path(@cocktail)
  end

  def review_params
    params.require(:review).permit(:name, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_search.html.erb
<%= simple_form_for :search, url: search_path, method: "GET", html: { class: 'p-3 form-inline' } do |f| %>
  <%= f.input :name, label: false, placeholder: 'search', input_html: {value: ""} %>
<% end %>

app/views/cocktails/edit.html.erb
<div class='container mt-4 p-3 rounded shadow'>
  <h1>Update cocktail name</h1>
  <hr>
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file%>
    <%= f.submit 'change', class:'btn btn-info mt-3'%>
  <% end %>
</div>

app/views/cocktails/index.html.erb
<h1>Cocktail Menu</h1>
<!-- link to add new cocktail -->
<%= link_to new_cocktail_path do %>
  <i class="fas fa-glass-martini"></i>
<% end %>
<!-- container for coktail grid -->
<div class='container'>
  <!-- cocktail grid -->
  <div class="card-cocktail-grid">
    <!-- iterating through cocktails -->
    <% @cocktails.each do |cocktail| %>
    <!-- if cocktail has photo define variable img -->
      <% if cocktail.photo.attached? %>
        <% img = cl_image_path(cocktail.photo.key)%>
      <% end %>
      <!-- cocktail card -->
      <div class="card-cocktail-index" style="background-image:url('<%= img %>'); background-repeat: no-repeat; background-size: cover">
        <div>
          <h2><%= link_to cocktail.name, cocktail_path(cocktail)  %></h2>
        </div>
        <!-- fontawesome icons which link to edit and destory actions -->
        <div>
          <%= link_to edit_cocktail_path(cocktail) do %>
            <i class="fas fa-pencil-alt"></i>
          <% end %>
          <%= link_to cocktail_path(cocktail), method: :delete, data: { confirm:'Are you sure?'} do %>
            <i class="fas fa-trash"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class='container mt-4 p-3 rounded shadow'>
<h1>New cocktail</h1>
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file%>
  <%= f.submit 'mix', class:'btn btn-info mt-3' %>
<% end %>
</div>

app/views/cocktails/search.html.erb
<h1>cocktails</h1>


<div class='card-cocktail-grid'>
<% @cocktails.each do |cocktail| %>
  <% if cocktail.photo.attached? %>
    <% img = cl_image_path(cocktail.photo.key)%>
  <% end %>
  <div class="card-cocktail-index" style="background-image:url('<%= img %>'); background-repeat: no-repeat; background-size: cover">
    <h2><%= link_to cocktail.name, cocktail_path(cocktail)  %></h2>
  </div>
<% end %>
</div>

app/views/cocktails/show.html.erb
<% if @cocktail.photo.attached? %>
    <% img = cl_image_path(@cocktail.photo.key)%>
<% end %>

<div class="container">
  <div class="container-flex">
    <div class="card-cocktail-index" style="background-image:url('<%= img %>'); background-repeat: no-repeat; background-size: cover">
      <h2><%= @cocktail.name %></h2>
    </div>
    <div class="card-ingredients">
      <h3>Description</h3>
      <p><%= @cocktail.description %></p>
      <h3>Ingredients</h3>
      <div class="list-ingredients">
      <ul>
        <% @cocktail.doses.each do |dose| %>
        <li>
            <%= link_to dose_path(dose), method: :delete, data: { confirm:'Are you sure?'} do %>
            <i class="delete fas fa-times-circle"></i>
            <% end %>
            <%= dose.ingredient.name %>  (<%= dose.description %>)
        </li>
        <% end %>
      </div>
      </ul>
      <%= render '/doses/new', { dose: Dose.new, url: cocktail_doses_path(@cocktail.id) } %>
    </div>
  <div class="card-reviews">
    <h3>Reviews</h3>
    <div class="review">
      <% @cocktail.reviews.each do |review| %>
      <%= link_to review_path(review), method: :delete, data: { confirm:'Are you sure?'} do %>
        <i class="delete fas fa-times-circle"></i>
      <% end %>
      <% review.rating.times do %>
        <i class="rating fas fa-star"></i>
      <% end %>
      ( <%= review.name %> )
      <p><%= review.content %></p>
      <% end %>
    </div>
    <%= render '/reviews/new', { review: Review.new, url: cocktail_reviews_path(@cocktail.id) } %>
  </div>
  </div>
</div>

app/views/doses/_new.html.erb
<div class='px-3 pb-3'>
  <hr>
  <h3>Add ingredient</h3>
  <%= simple_form_for dose, url: url do |f| %>
    <%= f.association :ingredient %>
    <%= f.input :description, placeholder: 'e.g. quantity' %>
    <%= f.submit "Add ingredient", class:"btn btn-info" %>
  <% end %>
</div>

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<p>Find me in app/views/doses/edit.html.erb</p>

app/views/doses/new.html.erb
<div class='container mt-4 p-3 rounded shadow'>
<h1>New measure</h1>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <!-- <a class="navbar-item navbar-brand" href="#">Mr Cocktail</a> -->
      <button class="navbar-item navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-item navbar-toggler-icon"></span>
      </button>
      <div class="navbar-item collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="navbar-item nav-item active">
            <a class="navbar-item nav-link" href=<%= root_path %>> Cocktails <span class="sr-only">(current)</span></a>
          </li>
          <li class="navbar-item nav-item">
            <a class="navbar-item nav-link" href=<%= new_cocktail_path %>> Add cocktail </a>
          </li>
          <li class="navbar-item nav-item">
            <%= render 'cocktails/search' %>
          </li>

        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Home page</h1>
<%= link_to 'Cocktails', cocktails_path %>

app/views/reviews/_new.html.erb
<div class='px-3 pb-3'>
  <hr>
  <h3>Add review</h3>
  <%= simple_form_for review, url: url do |f| %>
    <%= f.input :name %>
    <%= f.input :content %>
    <%= f.input :rating, collection: [0, 1, 2, 3, 4, 5] %>
    <%= f.submit "Add review", class:"btn btn-info" %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<div class='px-3 pb-3'>
  <hr>
  <h3>Add review</h3>
  <%= simple_form_for [@cocktail, @review] do |f| %>
    <%= f.input :name %>
    <%= f.input :content %>
    <%= f.input :rating, collection: [0, 1, 2, 3, 4, 5] %>
    <%= f.submit "Add review", class:"btn btn-info" %>
  <% end %>
</div>